Addition of hero component can be seen hero.html in src
ComputerSocietyVITC/docHub pull request #22
Opened 2022-12-30 20:30 UTC by 0sigma101

Signed-off-by: 0sigma101 <pallav.gupta2021@vitstudent.ac.in>

2023-01-02 08:04 UTC, AbhijithGanesh requested changes

2023-01-02 08:04 UTC, AbhijithGanesh commented on src/hero.css
> +@tailwind utilities;
This part of the code is not required as it is already covered in [base.css](https://github.com/ComputerSocietyVITC/docHub/blob/master/css/base.css)

2023-01-02 08:04 UTC, AbhijithGanesh commented on src/hero.html
> +    </article>
Only this bit of code is required if you re-wrote this in JSX

To learn what JSX is:
- [JSX from the React Team](https://reactjs.org/docs/introducing-jsx.html)
- [JSX - A comprehensive guide](https://facebook.github.io/jsx/)

2023-01-02 08:04 UTC, AbhijithGanesh commented on tailwind.config.js
> +      fontSize: {
These changes shouldn't be made. They're strongly not welcome. @porridgewithraisins @cool-pants

2023-01-05 07:12 UTC, mainak-affinsys commented
What even?

2023-01-05 17:03 UTC, 0sigma101 commented on tailwind.config.js
> +    },
Do i need to change spacing too it actually does not interfere with the code

2023-01-07 10:56 UTC, cool-pants commented
Why is the component named 'Hero', any specific reason for this change? What new things does it add/ change. Why is this required? Please specify all of this in the PR.

2023-01-07 11:02 UTC, 0sigma101 commented
> Why is the component named 'Hero', any specific reason for this change? What new things does it add/ change. Why is this required? Please specify all of this in the PR.

Hero is a synonym for website banners and that are used to put up advertisements but in our case we use it to put title

2023-02-03 17:08 UTC, AbhijithGanesh requested changes

2023-02-03 17:08 UTC, AbhijithGanesh commented on tailwind.config.js
> +    },
We shouldn't be custom styling like this

2023-02-06 15:12 UTC, 0sigma101 commented
Hey @AbhijithGanesh can please review my PR and the changes made.

2023-02-06 15:56 UTC, AbhijithGanesh commented
@0sigma101 I'll review

2023-02-11 17:11 UTC, 0sigma101 commented
@AbhijithGanesh Please review. I the responsive is top notch now

2023-03-01 05:35 UTC, AbhijithGanesh approved these changes
LGTM

2023-03-01 05:35 UTC, AbhijithGanesh commented on tailwind.config.js
>      },
LGTM

2023-03-01 05:35 UTC, AbhijithGanesh commented on src/pages/index.tsx
>            <Footer />
Re-strcturing

2023-03-01 05:37 UTC, AbhijithGanesh approved these changes
LGTM -> Changes after footer rebase

2023-03-01 05:37 UTC, merged