updated image links in mdx files
ComputerSocietyVITC/docHub pull request #26
Opened 2023-02-14 04:58 UTC by sam-shervin

- updated all the foreign image links in the mdx files to GitHub image links.
- lookup feature in discord.mdx did not work and so the mdx code is updated to make it work

2023-02-27 15:43 UTC, AdityaSai2004 approved these changes
Can proceed with merging

2023-02-27 15:44 UTC, AdityaSai2004 approved these changes
No issues found

2023-02-27 16:37 UTC, AdityaSai2004 requested changes
User content can be collected at a later point

2023-02-27 16:50 UTC, sam-shervin commented
user content part removed (can be added at a later point)

2023-02-27 16:53 UTC, sam-shervin commented
> User content can be collected at a later point

user content part removed (can be added at a later point)

2023-02-28 14:35 UTC, AdityaSai2004 approved these changes
Approved

2023-03-01 05:24 UTC, AbhijithGanesh requested changes

2023-03-01 05:24 UTC, AbhijithGanesh commented on tailwind.config.js
> -  content: ["./src/**/*.{js,jsx,ts,tsx, md. mdx}"],
Good catch!

2023-03-01 05:24 UTC, AbhijithGanesh commented on src/scripts/scripts.tsx
> +
Nice work but I would already add `_blank` Attribute!

2023-03-01 05:24 UTC, AbhijithGanesh commented on src/pages/index.tsx
> +            </section>
Redundant Change

2023-03-01 05:24 UTC, AbhijithGanesh commented on src/designs/static.tsx
> +      {new_tab(document)}
I'll approve this for the mean time, but this should be done a tad bit better!

2023-03-01 05:24 UTC, AbhijithGanesh commented on src/content/working-with-neural-networks.mdx
> +- If one has a strong enough pc(with at least 16 GB RAM, M.2 SSD, RTX2080 super , i7 11th gen or ryzen 7 5000 series) they can do it on jupyter([https://jupyter.org/](https://jupyter.org/)) else use
Good Catch

2023-03-01 05:24 UTC, AbhijithGanesh commented on src/content/native-android-app.mdx
> +![image](https://user-images.githubusercontent.com/121488288/218552812-a5654850-a1c9-4dd8-9d17-797ff05e019e.png)
Great move!

2023-03-01 05:24 UTC, AbhijithGanesh commented on src/content/introduction-to-react-part-one.mdx
> +![image](https://user-images.githubusercontent.com/121488288/218552344-e5aa17cf-5d2c-4785-9a50-f659e027a6a6.png)
Good work again

2023-03-01 05:24 UTC, AbhijithGanesh commented on src/content/discord.mdx
> +
Great effotrts @sam-shervin

2023-03-01 05:24 UTC, AbhijithGanesh commented on src/content/deep-learning.mdx
> +[Documentation](https://docs.python.org/3.11/)
```suggestion
[Python Documentation](https://docs.python.org/3.11/)
```

2023-03-01 05:24 UTC, AbhijithGanesh commented on src/components/searchbar/searchbar.tsx
> +const SearchBar = (placeholder: any): JSX.Element => {
change the type from `any`

2023-03-01 05:24 UTC, AbhijithGanesh commented on src/components/searchbar/searchbar.tsx
> +    const [wordEntered, setWordEntered] = useState("");
Type cast according to the state types
```suggestion
    const [filteredData, setFilteredData] = useState<typeof data[]>();
    const [wordEntered, setWordEntered] = useState<string>("");
```

2023-03-01 05:24 UTC, AbhijithGanesh commented on package.json
> +    "node": "^19.6.0",
```suggestion
    "node": "^19.6.0",
```
Delete this

2023-03-01 17:34 UTC, sam-shervin commented on src/components/searchbar/searchbar.tsx
> +    const [wordEntered, setWordEntered] = useState("");
done

2023-03-01 17:34 UTC, sam-shervin commented on package.json
> +    "node": "^19.6.0",
done

2023-03-01 17:38 UTC, sam-shervin commented
> change the type from `any`

I hope most changes have been rectified on my part except for the type of placeholder in searchbar.tsx which I wasn't able to find. I request you review and accept the pull request as soon as possible.

2023-03-04 17:56 UTC, closed without merging